In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
!pip install wandb -qU
!pip install opencv-python kagglehub contractions num2words inflect jieba cn2an sacrebleu safetensors datasets

Requirement already satisfied: opencv-python in /usr/local/lib/python3.11/dist-packages (4.11.0.86)
Requirement already satisfied: kagglehub in /usr/local/lib/python3.11/dist-packages (0.3.12)
Collecting contractions
  Downloading contractions-0.1.73-py2.py3-none-any.whl.metadata (1.2 kB)
Collecting num2words
  Downloading num2words-0.5.14-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: inflect in /usr/local/lib/python3.11/dist-packages (7.5.0)
Requirement already satisfied: jieba in /usr/local/lib/python3.11/dist-packages (0.42.1)
Collecting cn2an
  Downloading cn2an-0.5.23-py3-none-any.whl.metadata (10 kB)
Collecting sacrebleu
  Downloading sacrebleu-2.5.1-py3-none-any.whl.metadata (51 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.8/51.8 kB 5.0 MB/s eta 0:00:00
Requirement already satisfied: safetensors in /usr/local/lib/python3.11/dist-packages (0.5.3)
Collecting datasets
  Downloading datasets-3.5.1-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.21.2 in /usr/local/lib/python3.11/dist-packages (from opencv-python) (2.0.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from kagglehub) (24.2)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.11/dist-packages (from kagglehub) (6.0.2)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from kagglehub) (2.32.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from kagglehub) (4.67.1)
Collecting textsearch>=0.0.21 (from contractions)
  Downloading textsearch-0.0.24-py2.py3-none-any.whl.metadata (1.2 kB)
Collecting docopt>=0.6.2 (from num2words)
  Downloading docopt-0.6.2.tar.gz (25 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: more_itertools>=8.5.0 in /usr/local/lib/python3.11/dist-packages (from inflect) (10.7.0)
Requirement already satisfied: typeguard>=4.0.1 in /usr/local/lib/python3.11/dist-packages (from inflect) (4.4.2)
Collecting proces>=0.1.7 (from cn2an)
  Downloading proces-0.1.7-py3-none-any.whl.metadata (3.3 kB)
Collecting portalocker (from sacrebleu)
  Downloading portalocker-3.1.1-py3-none-any.whl.metadata (8.6 kB)
Requirement already satisfied: regex in /usr/local/lib/python3.11/dist-packages (from sacrebleu) (2024.11.6)
Requirement already satisfied: tabulate>=0.8.9 in /usr/local/lib/python3.11/dist-packages (from sacrebleu) (0.9.0)
Collecting colorama (from sacrebleu)
  Downloading colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: lxml in /usr/local/lib/python3.11/dist-packages (from sacrebleu) (5.4.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from datasets) (3.18.0)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (18.1.0)
Collecting dill<0.3.9,>=0.3.0 (from datasets)
  Downloading dill-0.3.8-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from datasets) (2.2.2)
Collecting xxhash (from datasets)
  Downloading xxhash-3.5.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (12 kB)
Collecting multiprocess<0.70.17 (from datasets)
  Downloading multiprocess-0.70.16-py311-none-any.whl.metadata (7.2 kB)
Collecting fsspec<=2025.3.0,>=2023.1.0 (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets)
  Downloading fsspec-2025.3.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.11/dist-packages (from datasets) (3.11.15)
Requirement already satisfied: huggingface-hub>=0.24.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (0.30.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.6.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (6.4.3)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.20.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.24.0->datasets) (4.13.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->kagglehub) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->kagglehub) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->kagglehub) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->kagglehub) (2025.1.31)
Collecting anyascii (from textsearch>=0.0.21->contractions)
  Downloading anyascii-0.3.2-py3-none-any.whl.metadata (1.5 kB)
Collecting pyahocorasick (from textsearch>=0.0.21->contractions)
  Downloading pyahocorasick-2.1.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (13 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Downloading contractions-0.1.73-py2.py3-none-any.whl (8.7 kB)
Downloading num2words-0.5.14-py3-none-any.whl (163 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 163.5/163.5 kB 13.8 MB/s eta 0:00:00
Downloading cn2an-0.5.23-py3-none-any.whl (224 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 224.9/224.9 kB 19.3 MB/s eta 0:00:00
Downloading sacrebleu-2.5.1-py3-none-any.whl (104 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 104.1/104.1 kB 11.4 MB/s eta 0:00:00
Downloading datasets-3.5.1-py3-none-any.whl (491 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 491.4/491.4 kB 41.1 MB/s eta 0:00:00
Downloading dill-0.3.8-py3-none-any.whl (116 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 11.8 MB/s eta 0:00:00
Downloading fsspec-2025.3.0-py3-none-any.whl (193 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 193.6/193.6 kB 19.6 MB/s eta 0:00:00
Downloading multiprocess-0.70.16-py311-none-any.whl (143 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.5/143.5 kB 16.0 MB/s eta 0:00:00
Downloading proces-0.1.7-py3-none-any.whl (137 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 137.7/137.7 kB 12.8 MB/s eta 0:00:00
Downloading textsearch-0.0.24-py2.py3-none-any.whl (7.6 kB)
Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Downloading portalocker-3.1.1-py3-none-any.whl (19 kB)
Downloading xxhash-3.5.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (194 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.8/194.8 kB 17.6 MB/s eta 0:00:00
Downloading anyascii-0.3.2-py3-none-any.whl (289 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 289.9/289.9 kB 23.9 MB/s eta 0:00:00
Downloading pyahocorasick-2.1.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (118 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 118.3/118.3 kB 11.6 MB/s eta 0:00:00
Building wheels for collected packages: docopt
  Building wheel for docopt (setup.py) ... done
  Created wheel for docopt: filename=docopt-0.6.2-py2.py3-none-any.whl size=13706 sha256=bc708e6724abbe58820d28b0dfce9187c1364bff32ae0938c3fe4a11751b50c6
  Stored in directory: /root/.cache/pip/wheels/1a/b0/8c/4b75c4116c31f83c8f9f047231251e13cc74481cca4a78a9ce
Successfully built docopt
Installing collected packages: docopt, xxhash, pyahocorasick, proces, portalocker, num2words, fsspec, dill, colorama, anyascii, textsearch, sacrebleu, multiprocess, cn2an, contractions, datasets
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2025.3.2
    Uninstalling fsspec-2025.3.2:
      Successfully uninstalled fsspec-2025.3.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torch 2.6.0+cu124 requires nvidia-cublas-cu12==12.4.5.8; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cublas-cu12 12.5.3.2 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cuda-cupti-cu12==12.4.127; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cuda-cupti-cu12 12.5.82 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cuda-nvrtc-cu12==12.4.127; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cuda-nvrtc-cu12 12.5.82 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cuda-runtime-cu12==12.4.127; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cuda-runtime-cu12 12.5.82 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cudnn-cu12==9.1.0.70; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cudnn-cu12 9.3.0.75 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cufft-cu12==11.2.1.3; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cufft-cu12 11.2.3.61 which is incompatible.
torch 2.6.0+cu124 requires nvidia-curand-cu12==10.3.5.147; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-curand-cu12 10.3.6.82 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cusolver-cu12==11.6.1.9; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cusolver-cu12 11.6.3.83 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cusparse-cu12==12.3.1.170; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cusparse-cu12 12.5.1.3 which is incompatible.
torch 2.6.0+cu124 requires nvidia-nvjitlink-cu12==12.4.127; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-nvjitlink-cu12 12.5.82 which is incompatible.
gcsfs 2025.3.2 requires fsspec==2025.3.2, but you have fsspec 2025.3.0 which is incompatible.
Successfully installed anyascii-0.3.2 cn2an-0.5.23 colorama-0.4.6 contractions-0.1.73 datasets-3.5.1 dill-0.3.8 docopt-0.6.2 fsspec-2025.3.0 multiprocess-0.70.16 num2words-0.5.14 portalocker-3.1.1 proces-0.1.7 pyahocorasick-2.1.0 sacrebleu-2.5.1 textsearch-0.0.24 xxhash-3.5.0

In [3]:
import torch
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [4]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

import unicodedata
import contractions
import inflect

import num2words
import cn2an
import jieba

import re
from nltk.corpus import stopwords
from num2words import num2words

import pandas as pd

from torch.utils.data import DataLoader, Dataset, SubsetRandomSampler

from datasets import load_dataset
from transformers import T5ForConditionalGeneration, T5Tokenizer
from safetensors.torch import load_file
from sklearn.model_selection import train_test_split

import wandb
import random

In [5]:
from transformers import T5ForConditionalGeneration, T5Tokenizer

model_weights_path = "drive/MyDrive/T5_fine_tuned_result/model_weights"
tokenizer_path = "drive/MyDrive/T5_fine_tuned_result/tokenizer_weights"

# Загрузка модели
model = T5ForConditionalGeneration.from_pretrained(model_weights_path)
tokenizer = T5Tokenizer.from_pretrained(tokenizer_path)

In [6]:
class CleanChineseText:
    def __init__(self, zh_text):
        self.zh_text = zh_text
    def escape_en_char(self):
        en_pattern = "[a-zA-Z]+"
        self.zh_text = re.sub(en_pattern, ' ', self.zh_text)
        return self
    def remove_enter_and_symbols(self):
        self.zh_text = re.sub(r'^\d+\.', '', self.zh_text).strip()
        return self
    def remove_gaps(self):
        self.zh_text = self.zh_text.replace(' ', '')
        return self
    def remove_punct(self):
        self.zh_text = self.zh_text.strip('，')
        return self

    def clean_all(self):
        # self.remove_punct()
        self.remove_enter_and_symbols()
        self.escape_en_char()
        self.remove_gaps()
        return (self.remove_enter_and_symbols()
          .escape_en_char()
          .remove_gaps()
          .remove_punct()
          .zh_text)

In [7]:
class CleanRussianText:
    def __init__(self, ru_text, remove_punctuation=True, convert_numbers=False):
        self.ru_text = ru_text
        self.remove_punctuation = remove_punctuation
        # self.convert_numbers = convert_numbers

    def to_one_style(self):
      # Lower case
      self.ru_text = self.ru_text.lower().strip()
      return self

    def remove_punctuation_symbols(self):
      if self.remove_punctuation:
        self.ru_text = re.sub(r'[^\w\s]', ' ', self.ru_text)  # пробел вместо пунктуации
        self.ru_text = re.sub(r'\s+', ' ', self.ru_text).strip()
      return self

    def combine_numbers(self):
      # combine numbers with a space, such as '40 000' to '40000'
      self.ru_text = re.sub(r'(?<=\d)\s(?=\d)', '', self.ru_text)
      return self

    def separate_numbers_and_words(self):
      # separate words like '11летнему' to '11 летнему'
      self.ru_text = re.sub(r'(\d+)([а-яА-Я]+)', r'\1 \2', self.ru_text)
      return self

    def separate_numbers_and_words(self):
        # separate words like '11летнему' to '11 летнему'
        self.ru_text = re.sub(r'(\d+)([а-яА-Я]+)', r'\1 \2', self.ru_text)
        return self

    def remove_double_spaces(self):
      self.ru_text = re.sub(r'\s+', ' ', self.ru_text)
      return self

    def remove_duplicate_symbols(self):
      # remove symbols like '????'
      self.ru_text = re.sub(r'(.)\1{3,}', r'\1\1', self.ru_text)
      return self

    def clean_all(self):
      # print(self.ru_text)
      return (self.to_one_style()
              .separate_numbers_and_words()
              .combine_numbers()
              .remove_punctuation_symbols()
              .remove_duplicate_symbols()
              .ru_text)

In [8]:
text = " ♫ \n как лёд сходит, и 3 000 лет идет к 11летнему Тиму ♫ 2025 год ????? 'Телефон 375 44 654 41 51. В городе 40 000 человек.'"
result = CleanRussianText(text).clean_all()
print(result)

как лёд сходит и 3000 лет идет к 11 летнему тиму 2025 год телефон 375446544151 в городе 400 человек

In [9]:
subtitle_dataset = load_dataset("open_subtitles", lang1="ru", lang2="zh_cn", trust_remote_code=True)

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

README.md:   0%|          | 0.00/7.45k [00:00<?, ?B/s]

open_subtitles.py:   0%|          | 0.00/6.22k [00:00<?, ?B/s]

Downloading data:   0%|          | 0.00/176M [00:00<?, ?B/s]

Generating train split: 0 examples [00:00, ? examples/s]

In [10]:
dataset_subset = pd.DataFrame(subtitle_dataset['train'])

In [11]:
df = dataset_subset[:700000]

In [12]:
df['cleaned_ru'] = df['translation'].apply(lambda x: CleanRussianText(x['ru']).clean_all())
df['cleaned_zh'] = df['translation'].apply(lambda x: CleanChineseText(x['zh_cn']).clean_all())

<ipython-input-12-41553e1c6f80>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['cleaned_ru'] = df['translation'].apply(lambda x: CleanRussianText(x['ru']).clean_all())
<ipython-input-12-41553e1c6f80>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['cleaned_zh'] = df['translation'].apply(lambda x: CleanChineseText(x['zh_cn']).clean_all())

In [13]:
len(df['cleaned_ru'])

700000

In [14]:
source_ru_train_subt, source_ru_val_subt, target_zh_train_subt, target_zh_val_subt = train_test_split(
    df['cleaned_ru'], df['cleaned_zh'], test_size=0.2, random_state=42)

In [15]:
def tokenize_dataset(source_ru, target_zh, tokenizer=tokenizer):
    prefix = 'translate to zh'
    source_ru_texts = [f'{prefix}: {text}' for text in source_ru]
    tokenized_ru_texts = tokenizer(source_ru_texts, truncation=True, padding=True, return_tensors='pt')
    target_zh_texts = tokenizer(target_zh.tolist(), truncation=True, padding=True, return_tensors='pt')
    return tokenized_ru_texts, target_zh_texts

class TokenizedTedCustomDataset(Dataset):
    def __init__(self, tokenized_ru_texts, target_zh_texts):
        self.ru_input_ids = tokenized_ru_texts['input_ids']
        self.attention_mask = tokenized_ru_texts['attention_mask']

        # self.target_zh = target_zh_texts_ids['input_ids']

        self.labels = target_zh_texts['input_ids']
        self.labels_mask = target_zh_texts['attention_mask']

    # def __getitem__(self, idx):
    #     return {
    #         'input_ids': self.source_ru[idx],
    #         # 'attention_mask': self.source_ru[idx]['attention_mask'].squeeze(0),
    #         'labels': torch.tensor([-100 if x == 0 else x for x in self.target_zh[idx]])
    #     }
    def __getitem__(self, idx):
        labels = self.labels[idx].clone()
        labels_mask = self.labels_mask[idx]

        # маскируем только паддинги
        labels[labels_mask == 0] = -100

        return {
            'input_ids': self.ru_input_ids[idx],
            'attention_mask': self.attention_mask[idx],
            'labels': labels
        }

    def __len__(self):
        return len(self.ru_input_ids)

In [16]:
tokenized_ru_texts_train, target_zh_texts_train = tokenize_dataset(source_ru_train_subt, target_zh_train_subt)
tokenized_ru_texts_val, target_zh_texts_val = tokenize_dataset(source_ru_val_subt, target_zh_val_subt)

In [17]:
from transformers import DataCollatorForSeq2Seq

data_collator = DataCollatorForSeq2Seq(tokenizer, model=model)

train_dataset = TokenizedTedCustomDataset(tokenized_ru_texts=tokenized_ru_texts_train, target_zh_texts=target_zh_texts_train)
test_dataset = TokenizedTedCustomDataset(tokenized_ru_texts=tokenized_ru_texts_val, target_zh_texts=target_zh_texts_val)

train_loader = DataLoader(dataset=train_dataset, batch_size=128, shuffle=False, collate_fn=data_collator)
test_loader = DataLoader(dataset=test_dataset, batch_size=256, shuffle=False, collate_fn=data_collator)

In [18]:
from torch.utils.data import Subset

# Generate subset for bleu score
subset_indices = list(range(2000))
bleu_subset = Subset(test_dataset, subset_indices)

# Generate DataLoader for bleu score
bleu_loader = DataLoader(dataset=bleu_subset, batch_size=128, shuffle=False, collate_fn=data_collator)

In [19]:
# from transformers import T5ForConditionalGeneration, T5Tokenizer

# device = 'cuda' #or 'cpu' for translate on cpu

# model_name = 'utrobinmv/t5_translate_en_ru_zh_small_1024'

# model = T5ForConditionalGeneration.from_pretrained(model_name)
# model.to(device)
# tokenizer = T5Tokenizer.from_pretrained(model_name)

# # model = T5ForConditionalGeneration.from_pretrained(pretrained_model_path)
# # model.to(device)
# # tokenizer = T5Tokenizer.from_pretrained(pretrained_tokenizer_path)

# prefix = 'translate to zh: '
# src_text = prefix + "Сдается квартира в хорошем состоянии на год и более."

# # translate Russian to Chinese
# input_ids = tokenizer(src_text, return_tensors="pt")

# generated_tokens = model.generate(**input_ids.to(device))

# result = tokenizer.batch_decode(generated_tokens, skip_special_tokens=True)
# print(result)
# #开发的目的就是向用户提供个性化的同步翻译。

In [20]:
from nltk import bleu
from sacrebleu import corpus_bleu
from nltk.translate.bleu_score import corpus_bleu, SmoothingFunction

smoothing = SmoothingFunction().method1
import time

def bleu_score(model, tokenizer, eval_pred_loader, device):
    bleu_dic = {}
    actual, predicted = [], []
    model.to(device)
    model.eval()

    with torch.no_grad():
        for batch in eval_pred_loader:
            input_ids = batch['input_ids'].to(device)
            attention_mask = batch['attention_mask'].to(device)
            labels = batch['labels'].to(device)

            # Восстановление паддингов вместо -100
            decoded_labels = labels.clone()
            decoded_labels[decoded_labels == -100] = tokenizer.pad_token_id



            # Генерация предсказаний
            # Когда ты генерируешь outputs = model.generate(input_ids),
            # иногда outputs содержит неправильные ID токенов, которых нет в словаре токенизатора (tokenizer).
            # Это вызывает ошибку в sentencepiece, которая стоит за T5Tokenizer!
            # Иными словами: модель генерит токен id, которого нет в твоём файле токенизатора.
            start = time.time()

            outputs = model.generate(
                input_ids,
                max_length=64,
                eos_token_id=tokenizer.eos_token_id,
                pad_token_id=tokenizer.pad_token_id
)
            print(f"Generate took: {time.time() - start:.2f}s")

            preds = tokenizer.batch_decode(outputs, skip_special_tokens=True)
            targets = tokenizer.batch_decode(decoded_labels, skip_special_tokens=True)

            # Токенизация ПО СИМВОЛЬНО для китайского языка
            actual.extend([[list(t)] for t in targets])
            predicted.extend([list(p) for p in preds])
            # print(actual, predicted)
    # Оптимизированный подсчет BLEU
    bleu_score = corpus_bleu(actual, predicted)
    bleu_dic['1-2-grams'] = corpus_bleu(actual, predicted, weights=(0.5, 0.5, 0, 0), smoothing_function=smoothing)
    bleu_dic['1-3-grams'] = corpus_bleu(actual, predicted, weights=(0.3, 0.3, 0.3, 0), smoothing_function=smoothing)
    bleu_dic['1-4-grams'] = corpus_bleu(actual, predicted, weights=(0.25, 0.25, 0.25, 0.25), smoothing_function=smoothing)

    return {"bleu": bleu_score, 'bleu_dic': bleu_dic}

In [21]:
len(bleu_loader.dataset)

2000

In [22]:
bleu_test_subt = bleu_score(model, tokenizer, bleu_loader, device)
print(bleu_test_subt)

/usr/local/lib/python3.11/dist-packages/transformers/data/data_collator.py:741: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at /pytorch/torch/csrc/utils/tensor_new.cpp:254.)
  batch["labels"] = torch.tensor(batch["labels"], dtype=torch.int64)
Both `max_new_tokens` (=1024) and `max_length`(=64) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Generate took: 146.63s

Both `max_new_tokens` (=1024) and `max_length`(=64) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Generate took: 67.05s

Both `max_new_tokens` (=1024) and `max_length`(=64) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Generate took: 73.38s

Both `max_new_tokens` (=1024) and `max_length`(=64) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Generate took: 68.29s

Both `max_new_tokens` (=1024) and `max_length`(=64) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Generate took: 66.80s

Both `max_new_tokens` (=1024) and `max_length`(=64) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Generate took: 68.49s

Both `max_new_tokens` (=1024) and `max_length`(=64) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Generate took: 66.87s

Both `max_new_tokens` (=1024) and `max_length`(=64) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Generate took: 66.95s

Both `max_new_tokens` (=1024) and `max_length`(=64) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Generate took: 67.01s

Both `max_new_tokens` (=1024) and `max_length`(=64) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Generate took: 66.62s

Both `max_new_tokens` (=1024) and `max_length`(=64) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Generate took: 66.94s

Both `max_new_tokens` (=1024) and `max_length`(=64) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Generate took: 66.84s

Both `max_new_tokens` (=1024) and `max_length`(=64) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Generate took: 66.91s

Both `max_new_tokens` (=1024) and `max_length`(=64) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Generate took: 1.53s

Both `max_new_tokens` (=1024) and `max_length`(=64) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Generate took: 66.95s

Both `max_new_tokens` (=1024) and `max_length`(=64) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Generate took: 44.55s
{'bleu': 0.009024002737418348, 'bleu_dic': {'1-2-grams': 0.023549877126483366, '1-3-grams': 0.02192079109998201, '1-4-grams': 0.009024002737418348}}

In [23]:
{
  'bleu': 0.1225,   # = 12.25%
  'bleu_dic': {
    '1-2-grams': 0.2282,   # = 22.82%
    '1-3-grams': 0.1983,   # = 19.83%
    '1-4-grams': 0.1225    # = 12.25%
  }
}

{'bleu': 0.1225,
 'bleu_dic': {'1-2-grams': 0.2282, '1-3-grams': 0.1983, '1-4-grams': 0.1225}}

In [24]:
{'bleu': 0.017452313239240094, 'bleu_dic': {'1-2-grams': 0.04230905551591624, '1-3-grams': 0.038562279660033116, '1-4-grams': 0.017452313239240094}}

{'bleu': 0.017452313239240094,
 'bleu_dic': {'1-2-grams': 0.04230905551591624,
  '1-3-grams': 0.038562279660033116,
  '1-4-grams': 0.017452313239240094}}

after tesing:
 {'bleu': 0.01817816826614059, 'bleu_dic': {'1-2-grams': 0.044103026601416365, '1-3-grams': 0.040001565361583495, '1-4-grams': 0.01817816826614059}}

In [ ]:
from transformers import Trainer, TrainingArguments

# Use wandb-core, temporary for wandb's new backend
wandb.require("core")
wandb.login()

training_args = TrainingArguments(
    max_grad_norm=1.0,
    output_dir='/drive/MyDrive/T5_fine_tuned_result/new/',
    per_device_train_batch_size=128,
    per_device_eval_batch_size=256,
    learning_rate=3e-5,
    num_train_epochs=3,
    logging_steps=2000,
    save_steps=5000,
    save_total_limit=1,
    seed=42,
    fp16=False,
    report_to="wandb",
    gradient_accumulation_steps=2
)


total_runs = 5

# This simple block simulates a training loop logging metrics
for run in range(total_runs):
    run_name = f"experiment_{run}"

    # Настраиваем wandb вручную для имени эксперимента
    wandb.init(project="zhrentybot", name=run_name)

    # Создаём тренер
    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_dataset,
        eval_dataset=test_dataset,
        tokenizer=tokenizer,
        data_collator=data_collator,
    )

    trainer.train()

    # Имитируем тренировку с логгингом метрик
    epochs = 2
    offset = random.random() / 5
    for epoch in range(2, epochs):
        acc = 1 - 2 ** -epoch - random.random() / epoch - offset
        loss = 2 ** -epoch + random.random() / epoch + offset
        wandb.log({"acc": acc, "loss": loss, "epoch": epoch})

    wandb.finish()

wandb: WARNING `wandb.require('core')` is redundant as it is now the default behavior.

wandb: Logging into wandb.ai. (Learn how to deploy a W&B server locally: https://wandb.me/wandb-server)
wandb: You can find your API key in your browser here: https://wandb.ai/authorize
wandb: Paste an API key from your profile and hit enter:

 ··········

wandb: WARNING If you're specifying your api key in code, ensure this code is not shared publicly.
wandb: WARNING Consider setting the WANDB_API_KEY environment variable, or running `wandb login` from the command line.
wandb: No netrc file found, creating one.
wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc
wandb: Currently logged in as: kotishova-lena (kotishova-lena-nonesuch-records) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

<ipython-input-25-5d4f8ace93e0>:34: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
wandb: WARNING The `run_name` is currently set to the same value as `TrainingArguments.output_dir`. If this was not intended, please specify a different run name by setting the `TrainingArguments.run_name` parameter.
Passing a tuple of `past_key_values` is deprecated and will be removed in Transformers v4.48.0. You should pass an instance of `EncoderDecoderCache` instead, e.g. `past_key_values=EncoderDecoderCache.from_legacy_cache(past_key_values)`.

<ipython-input-25-5d4f8ace93e0>:34: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

<ipython-input-25-5d4f8ace93e0>:34: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

In [ ]:
model.save_pretrained('drive/MyDrive/T5_fine_tuned_result/model_weights/')

In [ ]:
tokenizer.save_pretrained("drive/MyDrive/T5_fine_tuned_result/tokenizer_weights")

In [ ]:
import torch
import gc

def free_memory():
    torch.cuda.empty_cache()
    gc.collect()
free_memory()

In [ ]:
bleu_test_subt_after = bleu_score(model, tokenizer, bleu_loader, device)
print(bleu_test_subt_after)

In [ ]:
import kagglehub
from torch.utils.data import Dataset, DataLoader, SubsetRandomSampler

# Download latest version
path = kagglehub.dataset_download("averkij/russian-chinese-parallel-corpora")

print("Path to dataset files:", path)